### ISSUE TITLE
[Feature Request]: Better tagging

### ISSUE THREAD

**Issue by Its4Nik** [Its4Nik/DockStat-frontend#13]
### Functionality

Well we need a better tagging system.

Tagging every container on its own is tideous and annoying.

### Where should this button / dropdown / JSON value / ... be placed?

Proposal:

Add a tags.yaml to the backend which assigns the correct tags to each container automatically so you only have to add a container name and not the whole tag again....

### Backend and/or Frontend?

Backend

**Comment by Its4Nik** [comment]
Fixed tagging system.

New way of tagging:


```yaml
mintimeout: 10000 # The minimum time to wait before querying the same server again, defaults to 5000 Ms

log:
  logsize: 10 # Specify the Size of the log files in MB, default is 1MB
  LogCount: 1 # How many log files should be kept in rotation. Default is 5

tags:
  raspberry: red-200
  private: violet-400

hosts:
  YourHost1:
    url: hetzner
    port: 2375

container:
  dozzle: # Container name
    link: https://github.com
    icon: minecraft.png
    tags: private,raspberry
```
